name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   permissions:
      id-token: write
      contents: read
   env:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
#     # AWS_REGION: 'us-west-1'
   steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: us-east-2
   #        role-to-assume: arn:aws:iam::xxxxxx:role/githubactions
  #        role-session-name: GithubActionsSession
      - run: aws sts get-caller-identity   

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=demo-tfstate-s3-backend-01" -backend-config="key=${{ github.repository }}/terraform.tfstate" -backend-config="region=eu-west-1"
        
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        
